app = "hasiimusicbot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

# ğŸ”¥ Ù…ÙˆØ§ØµÙØ§Øª Ø§Ù„Ø®Ø§Ø¯Ù… (TITANIUM SPECS) ğŸ”¥
[[vm]]
  cpu_kind = "performance"  # Ù„Ø§Ø²Ù… performance Ø¹Ø´Ø§Ù† ÙŠÙ‚Ø¨Ù„ 16 ÙƒÙˆØ±
  cpus = 16                 # 16 Cores
  memory_mb = 92160         # 90 GB RAM (90 * 1024)
